name: Gradle Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Set up JDK 17
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        java-version: 17
        distribution: oracle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629 # v2.4.2

    - name: Execute Gradle build
      run: |
        ./gradlew build
        ./gradlew combinedjavadoc
        ./gradlew combinedWindowsZip
        ./gradlew combinedLinuxZip
        ./gradlew combinedrpm
        ./gradlew combineddeb
